title: ENIGMA
description: a pulp adventure roleplaying game
theme: just-the-docs

url: https://www.enigma-rpg.com

favicon_ico: "/assets/favicon.png"

color_scheme: default

# Load custom SCSS file
just_the_docs:
  custom_css:
    - _sass/custom/_custom.scss