title: ENIGMA
description: a pulp adventure roleplaying game
theme: just-the-docs

url: https://Andrew-Pelham.github.io/enigma-rpg

just_the_docs:
  color_scheme: auto
favicon_ico: "/assets/favicon.png"

# Custom styles
sass:
  load_paths:
    - _sass
  style: compressed

# Include custom SCSS file
include:
  - _sass/custom/_custom.scss